In [1]:
import torch

### Tensor

In [2]:
x = torch.empty(5, 3)
x

tensor([[1.0102e-38, 1.0286e-38, 1.0194e-38],
        [9.6429e-39, 9.2755e-39, 9.1837e-39],
        [9.3674e-39, 1.0745e-38, 1.0653e-38],
        [9.5510e-39, 1.0561e-38, 1.0194e-38],
        [1.1112e-38, 1.0561e-38, 9.9184e-39]])

In [3]:
x = torch.rand(5, 3)
x

tensor([[0.0091, 0.8218, 0.3946],
        [0.3170, 0.6028, 0.1173],
        [0.3248, 0.9343, 0.7380],
        [0.9005, 0.4581, 0.4142],
        [0.7910, 0.8975, 0.9258]])

In [5]:
x = torch.zeros(5, 3, dtype=torch.long)
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [7]:
x = torch.tensor([5.5, 3])
x

tensor([5.5000, 3.0000])

In [8]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.6994,  0.6906, -0.9677],
        [ 0.5433, -0.0171,  1.6092],
        [ 0.3993,  0.7994,  0.6424],
        [ 0.2117, -1.2173, -0.7858],
        [ 0.1422, -1.2047,  0.8554]])


In [9]:
print(x.size())

torch.Size([5, 3])


### Operations

In [10]:
y = torch.rand(5, 3)
print(x + y)

print(torch.add(x, y))

result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 1.0590,  1.6621, -0.4331],
        [ 0.8140,  0.6616,  1.9078],
        [ 1.0978,  1.7494,  0.8640],
        [ 0.6700, -1.1203,  0.1959],
        [ 0.7643, -0.7773,  1.8273]])
tensor([[ 1.0590,  1.6621, -0.4331],
        [ 0.8140,  0.6616,  1.9078],
        [ 1.0978,  1.7494,  0.8640],
        [ 0.6700, -1.1203,  0.1959],
        [ 0.7643, -0.7773,  1.8273]])
tensor([[ 1.0590,  1.6621, -0.4331],
        [ 0.8140,  0.6616,  1.9078],
        [ 1.0978,  1.7494,  0.8640],
        [ 0.6700, -1.1203,  0.1959],
        [ 0.7643, -0.7773,  1.8273]])


In [11]:
# Any operation that mutates a tensor in-place is post-fixed with an _. For example: x.copy_(y), x.t_(), will change x.
y.add_(x)
print(y)

tensor([[ 1.0590,  1.6621, -0.4331],
        [ 0.8140,  0.6616,  1.9078],
        [ 1.0978,  1.7494,  0.8640],
        [ 0.6700, -1.1203,  0.1959],
        [ 0.7643, -0.7773,  1.8273]])


In [12]:
# Resizing: If you want to resize/reshape tensor, you can use torch.view
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [15]:
#  only one element tensor, use .item() 
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.2976])
0.29763269424438477


### Numpy Bridge

In [16]:
a = torch.ones(5)
print(a)
b = a.numpy()
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [17]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [19]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)    # a + 1
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


array([3., 3., 3., 3., 3.])

### CUDA Tensors

In [24]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
else:
    device = torch.device("cpu")
y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
x = x.to(device)                       # or just use strings ``.to("cuda")``
z = x + y
print(z)
print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

tensor([1.2976], device='cuda:0')
tensor([1.2976], dtype=torch.float64)
